import type { MainDeckCatalogEntry } from "./catalog-types";

export const MAIN_DECK_CATALOG: MainDeckCatalogEntry[] = [
  { count: 4, name: "accio", power: {} },
  { count: 25, name: "stupefy", power: {} },
  { count: 12, name: "protego", power: {} },
  { count: 3, name: "azkaban", power: { jailed: true } },
  { count: 6, name: "butterbeer", power: {} },
  {
    count: 4,
    fileNames: ["expelliarmus_1", "expelliarmus_2", "expelliarmus_3"],
    name: "expelliarmus",
    power: {},
  },
  { name: "larch_wand", power: { range: 4 } },
  { name: "yew_wand", power: { range: 4 } },
  { name: "aspen_wand", power: { range: 3 } },
  { name: "holly_wand", power: { range: 2, "yew-immunity": true } },
  { name: "elder_wand", power: {} },
  { name: "fiendfyre", power: {} },
  { count: 2, name: "broomstick", power: { distance: 1 } },
  { name: "polyjuice_potion", power: { distance: -1 } },
  { name: "resurrection_stone", power: {} },
  { name: "expecto_patronum", power: {} },
  { count: 3, name: "wizards_duel", power: {} },
  { name: "weasleys_wizard_weezes", power: {} },
  { count: 2, name: "vanishing_cabinet", power: {} },
  { name: "invisibility_cloak", power: {} },
  { name: "felix_felicis", power: {} },
  { count: 2, name: "dementors", power: {} },
  { name: "apparate", power: {} },
  { name: "three_broomsticks", power: {} },
  { count: 2, name: "honeydukes", power: {} },
  { name: "garroting_gas", power: {} },
  { count: 2, name: "diagon_alley", power: {} },
];
