import type { CharacterCatalogEntry } from "./catalog-types";

export const CHARACTER_CATALOG: CharacterCatalogEntry[] = [
  {
    fileName: "albus_dumbledore",
    name: "Albus Dumbledore",
    shortName: "Dumbledore",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "arthur_weasley",
    name: "Arthur Weasley",
    shortName: "Arthur",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "bellatrix_lestrange",
    name: "Bellatrix Lestrange",
    shortName: "Bellatrix",
    house: "S",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "cedric_diggory",
    name: "Cedric Diggory",
    shortName: "Cedric",
    house: "H",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "dobby",
    name: "Dobby",
    shortName: "Dobby",
    house: "",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "dolores_umbridge",
    name: "Dolores Umbridge",
    shortName: "Umbridge",
    house: "S",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "draco_malfoy",
    name: "Draco Malfoy",
    shortName: "Draco",
    house: "S",
    health: 3,
    maxHealth: 3,
    power: {},
  },
  {
    fileName: "fenrir_greyback",
    name: "Fenrir Greyback",
    shortName: "Fenrir",
    house: "S",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "fred_and_george",
    name: "Fred & George Weasley",
    shortName: "Fred & George",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "gilderoy_lockhart",
    name: "Gilderoy Lockhart",
    shortName: "Gilderoy",
    house: "R",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "ginny_weasley",
    name: "Ginny Weasley",
    shortName: "Ginny",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "harry_potter",
    name: "Harry Potter",
    shortName: "Harry",
    house: "G",
    health: 3,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "hermione_granger",
    name: "Hermione Granger",
    shortName: "Hermione",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "james_potter",
    name: "James Potter",
    shortName: "James",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "lily_potter",
    name: "Lily Potter",
    shortName: "Lily",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "lucius_malfoy",
    name: "Lucius Malfoy",
    shortName: "Lucius",
    house: "S",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "luna_lovegood",
    name: "Luna Lovegood",
    shortName: "Luna",
    house: "R",
    health: 3,
    maxHealth: 3,
    power: {},
  },
  {
    fileName: "mad-eye_moody",
    name: 'Alastor "Mad-Eye" Moody',
    shortName: "Mad-Eye",
    house: "R",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "minerva_mchonagall",
    name: "Minerva McGonagall",
    shortName: "McGonagall",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "molly_weasley",
    name: "Molly Weasley",
    shortName: "Molly",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "mundungus_fletcher",
    name: "Mundungus Fletcher",
    shortName: "Mundungus",
    house: "S",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "neville_longbottom",
    name: "Neville Longbottom",
    shortName: "Neville",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "nymphadora_tonks",
    name: "Nymphadora Tonks",
    shortName: "Tonks",
    house: "H",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "peeves",
    name: "Peeves",
    shortName: "Peeves",
    house: "",
    health: 3,
    maxHealth: 3,
    power: {},
  },
  {
    fileName: "peter_pettigrew",
    name: "Peter Pettigrew",
    shortName: "Pettigrew",
    house: "G",
    health: 3,
    maxHealth: 3,
    power: {},
  },
  {
    fileName: "remus_lupin",
    name: "Remus Lupin",
    shortName: "Lupin",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "ron_weasley",
    name: "Ron Weasley",
    shortName: "Ron",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "rubeus_hagrid",
    name: "Rubeus Hagrid",
    shortName: "Hagrid",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "severus_snape",
    name: "Severus Snape",
    shortName: "Snape",
    house: "S",
    health: 3,
    maxHealth: 3,
    power: {},
  },
  {
    fileName: "sirius_black",
    name: "Sirius Black",
    shortName: "Sirius",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "voldemort",
    name: "Voldemort",
    shortName: "Voldemort",
    house: "S",
    health: 3,
    maxHealth: 3,
    power: {},
  },
];
