const mainDeck = () => {
  let houses = Array(82)
    .fill("G", 0, 20)
    .fill("R", 20, 41)
    .fill("S", 41, 61)
    .fill("H", 61, 82);
  let accio = Array(4).fill({ name: "accio", power: {} }),
    stupefy = Array(25).fill({ name: "stupefy", power: {} }),
    protego = Array(12).fill({ name: "protego", power: {} }),
    azkaban = Array(3).fill({ name: "azkaban", power: { jailed: true } }),
    beer = Array(6).fill({ name: "butterbeer", power: {} }),
    expelliarmus = [...Array(4)].map((e) => ({
      name: "expelliarmus",
      fileName: "expelliarmus_" + Math.ceil(Math.random() * 3),
      power: {},
    })),
    others = [
      { name: "larch_wand", power: { range: 4 } },
      { name: "yew_wand", power: { range: 4 } },
      { name: "aspen_wand", power: { range: 3 } },
      { name: "holly_wand", power: { range: 2, "yew-immunity": true } },
      { name: "elder_wand", power: {} },
      { name: "fiendfyre", power: {} },
      { name: "broomstick", power: { distance: 1 } },
      { name: "broomstick", power: { distance: 1 } },
      { name: "polyjuice_potion", power: { distance: -1 } },
      { name: "resurrection_stone", power: {} },
      { name: "expecto_patronum", power: {} },
      { name: "wizards_duel", power: {} },
      { name: "wizards_duel", power: {} },
      { name: "wizards_duel", power: {} },
      { name: "weasleys_wizard_weezes", power: {} },
      { name: "vanishing_cabinet", power: {} },
      { name: "vanishing_cabinet", power: {} },
      { name: "invisibility_cloak", power: {} },
      { name: "felix_felicis", power: {} },
      { name: "dementors", power: {} },
      { name: "dementors", power: {} },
      { name: "apparate", power: {} },
      { name: "three_broomsticks", power: {} },
      { name: "honeydukes", power: {} },
      { name: "honeydukes", power: {} },
      { name: "garroting_gas", power: {} },
      { name: "diagon_alley", power: {} },
      { name: "diagon_alley", power: {} },
    ],
    deck = [
      ...accio,
      ...stupefy,
      ...protego,
      ...azkaban,
      ...beer,
      ...others,
      ...expelliarmus,
    ];

  deck.forEach((v, i) => {
    deck[i] = {
      id: i,
      name: v.name,
      fileName: v.fileName || v.name,
      power: v.power,
      house: houses.splice(Math.floor(Math.random() * houses.length), 1)[0],
    };
  });

  return deck;
};

const characters = [
  {
    fileName: "albus_dumbledore",
    name: "Albus Dumbledore",
    shortName: "Dumbledore",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "arthur_weasley",
    name: "Arthur Weasley",
    shortName: "Arthur",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "bellatrix_lestrange",
    name: "Bellatrix Lestrange",
    shortName: "Bellatrix",
    house: "S",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "cedric_diggory",
    name: "Cedric Diggory",
    shortName: "Cedric",
    house: "H",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "dobby",
    name: "Dobby",
    shortName: "Dobby",
    house: "",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "dolores_umbridge",
    name: "Dolores Umbridge",
    shortName: "Umbridge",
    house: "S",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "draco_malfoy",
    name: "Draco Malfoy",
    shortName: "Draco",
    house: "S",
    health: 3,
    maxHealth: 3,
    power: {},
  },
  {
    fileName: "fenrir_greyback",
    name: "Fenrir Greyback",
    shortName: "Fenrir",
    house: "S",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "fred_and_george",
    name: "Fred & George Weasley",
    shortName: "Fred & George",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "gilderoy_lockhart",
    name: "Gilderoy Lockhart",
    shortName: "Gilderoy",
    house: "R",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "ginny_weasley",
    name: "Ginny Weasley",
    shortName: "Ginny",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "harry_potter",
    name: "Harry Potter",
    shortName: "Harry",
    house: "G",
    health: 3,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "hermione_granger",
    name: "Hermione Granger",
    shortName: "Hermione",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "james_potter",
    name: "James Potter",
    shortName: "James",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "lily_potter",
    name: "Lily Potter",
    shortName: "Lily",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "lucius_malfoy",
    name: "Lucius Malfoy",
    shortName: "Lucius",
    house: "S",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "luna_lovegood",
    name: "Luna Lovegood",
    shortName: "Luna",
    house: "R",
    health: 3,
    maxHealth: 3,
    power: {},
  },
  {
    fileName: "mad-eye_moody",
    name: 'Alastor "Mad-Eye" Moody',
    shortName: "Mad-Eye",
    house: "R",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "minerva_mchonagall",
    name: "Minerva McGonagall",
    shortName: "McGonagall",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "molly_weasley",
    name: "Molly Weasley",
    shortName: "Molly",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "mundungus_fletcher",
    name: "Mundungus Fletcher",
    shortName: "Mundungus",
    house: "S",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "neville_longbottom",
    name: "Neville Longbottom",
    shortName: "Neville",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "nymphadora_tonks",
    name: "Nymphadora Tonks",
    shortName: "Tonks",
    house: "H",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "peeves",
    name: "Peeves",
    shortName: "Peeves",
    house: "",
    health: 3,
    maxHealth: 3,
    power: {},
  },
  {
    fileName: "peter_pettigrew",
    name: "Peter Pettigrew",
    shortName: "Pettigrew",
    house: "G",
    health: 3,
    maxHealth: 3,
    power: {},
  },
  {
    fileName: "remus_lupin",
    name: "Remus Lupin",
    shortName: "Lupin",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "ron_weasley",
    name: "Ron Weasley",
    shortName: "Ron",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "rubeus_hagrid",
    name: "Rubeus Hagrid",
    shortName: "Hagrid",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "severus_snape",
    name: "Severus Snape",
    shortName: "Snape",
    house: "S",
    health: 3,
    maxHealth: 3,
    power: {},
  },
  {
    fileName: "sirius_black",
    name: "Sirius Black",
    shortName: "Sirius",
    house: "G",
    health: 4,
    maxHealth: 4,
    power: {},
  },
  {
    fileName: "voldemort",
    name: "Voldemort",
    shortName: "Voldemort",
    house: "S",
    health: 3,
    maxHealth: 3,
    power: {},
  },
];

module.exports = { mainDeck, characters };
